// A list of all actions in the system.
import { createTypes } from 'reduxsauce'

export default createTypes(`
  LOGIN_ATTEMPT
  LOGIN_SUCCESS
  LOGIN_FAILURE
  RECEIVE_TOKEN
  RECEIVE_ENTITIES

  LOGOUT

  REGISTER_ATTEMPT
  REGISTER_SUCCESS
  REGISTER_FAILURE

  DISCOVER_CHANNELS
  DISCOVER_CHANNELS_SUCCESS
  DISCOVER_CHANNELS_FAILED

  CREATE_CHANNEL
  CREATE_CHANNEL_SUCCESS
  CREATE_CHANNEL_FAILED
  FETCH_CHANNEL
  FETCH_CHANNEL_SUCCESS
  FETCH_CHANNEL_FAILED
  JOIN_CHANNEL
  JOIN_CHANNEL_SUCCESS
  JOIN_CHANNEL_FAILED
  OPEN_CHANNEL

  STARTUP
`)
